language: go
install:
  - export QINIU_SRC=$HOME/gopath/src
  - mkdir -p $QINIU_SRC/qiniupkg.com
  - mv $QINIU_SRC/github.com/qiniu/dyn $QINIU_SRC/qiniupkg.com/dyn
  - git clone --depth=50 git://github.com/qiniu/x.git $QINIU_SRC/qiniupkg.com/x
  - export TRAVIS_BUILD_DIR=$QINIU_SRC/qiniupkg.com/dyn
  - cd $TRAVIS_BUILD_DIR
  
